# Generated by Django 5.0.2 on 2024-05-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnippet', '0003_student_supervisor_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('document', models.FileField(upload_to='research_papers/')),
                ('authors', models.ManyToManyField(related_name='authored_papers', to='codesnippet.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesnippet.supervisor')),
            ],
        ),
    ]
