# Generated by Django 5.0.2 on 2024-05-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnippet', '0004_researchpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoutput',
            name='output_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
