# Generated by Django 5.0.2 on 2024-05-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnippet', '0006_team_student3'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('rate', models.FloatField()),
                ('sttl', models.IntegerField()),
                ('dload', models.FloatField()),
                ('swin', models.IntegerField()),
                ('stcpb', models.BigIntegerField()),
                ('dtcpb', models.BigIntegerField()),
                ('dwin', models.IntegerField()),
                ('ct_srv_src', models.IntegerField()),
                ('ct_state_ttl', models.IntegerField()),
                ('ct_src_dport_ltm', models.IntegerField()),
                ('ct_dst_sport_ltm', models.IntegerField()),
                ('ct_dst_src_ltm', models.IntegerField()),
                ('ct_srv_dst', models.IntegerField()),
                ('attack_cat', models.IntegerField()),
                ('prediction_gn', models.FloatField(blank=True, null=True)),
                ('prediction_gb', models.FloatField(blank=True, null=True)),
                ('prediction_lr', models.FloatField(blank=True, null=True)),
                ('prediction_lr_l1', models.FloatField(blank=True, null=True)),
                ('prediction_lr_l2', models.FloatField(blank=True, null=True)),
                ('prediction_gb_gscv', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
