# Generated by Django 5.0.2 on 2024-05-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesnippet', '0009_binaryprediction_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaryprediction',
            name='attack_cat',
        ),
    ]
